version: '3.4'
services:
    fsservice:
        image: mrsaydron/free-speak:dev

    rproxy:
        image: nginx
        links:
            - fsservice:fsservice
        ports:
            - 80:80
            - 443:443
        volumes:
            - ~/nginx:/etc/nginx
