FROM gradle:jdk11 as back

WORKDIR /code
COPY ./gradle /code/gradle
COPY ./src /code/src

COPY ./.prettierignore /code
COPY ./.prettierrc /code
COPY ./build.gradle /code
COPY ./checkstyle.xml /code
COPY ./gradle.properties /code
COPY ./settings.gradle /code
COPY ./sonar-project.properties /code

RUN gradle build

###############################################
FROM openjdk:11-jre-slim

EXPOSE 4000

WORKDIR /app
COPY --from=back /code/build/libs/lib-four-0.0.1-SNAPSHOT.jar free-speak.jar

CMD [ "java", "-Dspring.profiles.active=prod", "-jar", "free-speak.jar" ]
