name: Master_workflow
on:
  push:
    branches:
    - master

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#    - name: Validate Gradle wrapper
#      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#    - run: ./gradlew build
#    - uses: actions/upload-artifact@v2
#      with:
#        name: build_result
#        path: build/libs/lib-four-0.0.1-SNAPSHOT.jar
#        retention-days: 1

  package:
    runs-on: ubuntu-latest
#    needs: build
    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/download-artifact@v2
#      with:
#        name: build_result
#    - run: docker build -t cr.yandex/crpg1rhtqejenaohq3ja/free-speak:master -f Dockerfile .
    - run: echo ${{ yandexCloud.PASSWORD }}
#    - name: login
#      env:
#        PASSWORD: ${{ secrets.PASSWORD }}
#      run: echo docker login --username oauth --password env.PASSWORD cr.yandex
#    - run: docker push cr.yandex/crpg1rhtqejenaohq3ja/free-speak:master
